Refactor gitlab support
icapps/flutter-icapps-license pull request #27
Opened 2022-01-04 15:15 UTC by vanlooverenkoen

Fixed #22

2022-01-04 16:22 UTC, NicolaVerbeeck requested changes

2022-01-04 16:22 UTC, NicolaVerbeeck commented on bin/src/extension/github_extensions.dart
> +    const rawGithubUrl = 'https://raw.githubusercontent.com/';
Doubt

2022-01-05 08:36 UTC, NicolaVerbeeck approved these changes

2022-01-05 09:03 UTC, ikbendewilliam approved these changes

2022-01-05 10:48 UTC, merged